### ISSUE TITLE
It does not work if the model is based on User

### ISSUE THREAD

**Issue by zeornelas** [devsu/loopback-setup-remote-methods-mixin#10]
I tried to disable the methods of my user model (this model has User as base) and some methods (the methods inherited from other models) remain active.

**Comment by c3s4r** [comment]
Hi. Some methods are not removed because they are configured in an ACL. Have you tried using the `ignoreACL` option? Does that solve the issue?

**Comment by zeornelas** [comment]
@c3s4r thanks! It works! I don't know but I probably misread the ignoreAcl option description. I thought that it resulted in a different behaviour.
