### ISSUE TITLE
Any way to customize relation method as well?

### ISSUE THREAD

**Issue by dariusj18** [devsu/loopback-setup-remote-methods-mixin#13]
It seems that if I use "disableAllExcept" it also remove methods created for relations.

I imagine an extra option could be added to define relations and which methods should be disabled, maybe even a "*" key so that you can make all relations have the same disabled method by default (overridden by specificity)

I am new to loopback, so I'm not sure how difficult this would be, or if I'm barking up the wrong tree.  But this project seems to be the closest I have found to what I imagine.

**Comment by c3s4r** [comment]
Merged. Will be published soon.
