### ISSUE TITLE
Warning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by vqoph** [devsu/loopback-setup-remote-methods-mixin#2]
this warning disappear if i remove the mixin from my model-config file 
i use this mixin in my project with the following configuration :
```
...
"SetupRemoteMethods": {
      "ignoreACL": false,
      "disableAllExcept": []
    },
...
```

**Comment by c3s4r** [comment]
Hi @vqoph: Most probably it's not at issue with this module, but with loopback: See https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L191 and https://github.com/strongloop/loopback/issues/404. Anyways, @arielmcm, can you take a look when you have a chance?
