### ISSUE TITLE
Disable All Except GET is not working

### ISSUE THREAD

**Issue by F3L1X79** [devsu/loopback-setup-remote-methods-mixin#4]
Hi, thanks for this awesome module!
I tried:
"disableAllExcept": ["get"],

But it is not working. Any clues? Thanks

**Comment by c3s4r** [comment]
Try: `"disableAllExcept": ["find"]`. You can see the list of default remote methods at http://loopback.io/doc/en/lb3/Exposing-models-over-REST.html#predefined-remote-methods

**Comment by F3L1X79** [comment]
Amazing, thanks!
