### ISSUE TITLE
igoreACL not considered

### ISSUE THREAD

**Issue by mamartins** [devsu/loopback-setup-remote-methods-mixin#7]
If I create a model with this ACL:
````
        {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "accessType": "EXECUTE",
      "property": "getById"
    }
`````
or 
````
        {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "getById"
    } 
````

with the option 
````
    "SetupRemoteMethods": {
      "ignoreACL": false
    } 
````

I was expecting to see and work only the method get on the explorer but that is not true. Unless I specifically disable the other methods or use ```` disableAllExcept ```` all methods are available and usable

**Comment by c3s4r** [comment]
As stated in the README file, This option works together with `disable` and `disableAllExcept`.
