### ISSUE TITLE
slow for  many models, 

### ISSUE THREAD

**Issue by go2smartphone** [devsu/loopback-setup-remote-methods-mixin#9]
it takes long time to process all the models before the server start...
is it any way we can improve that?

**Comment by Hyperc0der** [comment]
`server.on('started', () => { ... })` causes it. ≈5 sec to process each model. Actually, what's the point to check if server is started for each model?

**Comment by c3s4r** [comment]
I just merged an improvement. Soon will be released as a new minor version.
